# Template used by unit-tests.yml
jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  timeoutInMinutes: 20
  steps:
    - script: $(Build.SourcesDirectory)\build.cmd /v:normal /p:Configuration=${{ parameters.configuration }} /p:CIBuild=true
      displayName: Build All Projects

    - task: PublishBuildArtifacts@1
      inputs:
        PathToPublish: '$(Build.SourcesDirectory)\artifacts\${{ parameters.configuration }}\log'
        ArtifactName: '${{ parameters.configuration }} Log folder'
        publishLocation: Container
      continueOnError: true
      condition: failed()

    - task: PublishBuildArtifacts@1
      inputs:
        PathToPublish: '$(Build.SourcesDirectory)\artifacts\${{ parameters.configuration }}\bin'
        ArtifactName: '${{ parameters.configuration }} Bin folder'
        publishLocation: Container
      continueOnError: true
      condition: failed()

    - task: PublishBuildArtifacts@1
      inputs:
        PathToPublish: '$(Build.SourcesDirectory)\artifacts\${{ parameters.configuration }}\VSSetup'
        ArtifactName: '${{ parameters.configuration }} VSSetup folder'
        publishLocation: Container
      continueOnError: true
      condition: failed()

    - task: PublishBuildArtifacts@1
      inputs:
        PathToPublish: '$(Build.SourcesDirectory)\artifacts\${{ parameters.configuration }}\TestResults'
        ArtifactName: '${{ parameters.configuration }} TestResults folder'
        publishLocation: Container
      continueOnError: true
      condition: failed()

    - task: PublishTestResults@2
      inputs:
        testRunner: 'xUnit'
        testResultsFiles: '**/*.xml'
        searchFolder: '$(Build.SourcesDirectory)\artifacts\${{ parameters.configuration }}\TestResults'
        configuration: '${{ parameters.configuration }}'
        publishRunAttachments: true
        failTaskOnFailedTests: true
      continueOnError: true
      condition: always()